"use strict";
angular.module("BlurAdmin.configs", []),
angular.module("BlurAdmin.configs").constant("backendProtocol", "http"),
angular.module("BlurAdmin.configs").constant("backendHost", "localhost:10010"),
angular.module("BlurAdmin.configs").constant("apiPath", "/api/v1"),
angular.module("BlurAdmin.configs").constant("tenantId", "c26d86bb2ea97e6332a25efd0447a09d"),
angular.module("BlurAdmin.configs").constant("backendProtocol", "https"),
angular.module("BlurAdmin.configs").constant("backendHost", "prod-starter-backend-ff12827fc4e309a44da3086cbb39a355.mybluemix.net"),
angular.module("BlurAdmin.configs").constant("backendPath", "/api/v1"),
angular.module("BlurAdmin.configs").constant("backendWebSocketPath", "/notifications"),
angular.module("BlurAdmin.configs").constant("authCallbackPath", "/"),
angular.module("BlurAdmin.configs").constant("customerICN", "999999");